version: '3.8'
services:
  api:
    build: ./backend
    container_name: vgtc_backend
    ports:
      - '80:3001'
      - '443:3001'
      - '3002:3002'
    volumes:
      - ./backend:/app
      - ../../../etc/letsencrypt/live/vgtc.ca/privkey.pem:/etc/letsencrypt/live/vgtc.ca/privkey.pem
      - ../../../etc/letsencrypt/live/vgtc.ca/fullchain.pem:/etc/letsencrypt/live/vgtc.ca/fullchain.pem
  client:
    build: ./frontend
    container_name: vgtc_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
